language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.m2"
before_script:
  - git clone https://github.com/coreos/jetcd.git
  - cd jetcd
  - git checkout 601afeb89794b4917ff690490d0ebf5de03fba56
  - mvn -Dmaven.test.skip=true install
  - cd ..
